source "http://rubygems.org"

group :test do
  gem 'rspec-rails'
  gem 'factory_girl'	
  gem 'capybara'
  gem 'spork'
	#following cucumber
  gem 'cucumber-rails'
  gem 'database_cleaner'
  #gem 'selenium-webdriver'	
end

# group :cucumber do end

# Specify your gem's dependencies in dc_core.gemspec
gemspec
